name: Benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run benchmarks weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggers

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run basic benchmark
      run: |
        python benchmarks/basic_benchmark.py
    
    - name: Run framework comparison
      run: |
        python benchmarks/compare_frameworks.py
    
    - name: Run scaling benchmark
      run: |
        python benchmarks/scaling_benchmark.py
    
    - name: Save benchmark results
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p benchmark-results
        echo "Benchmark run: $(date)" > benchmark-results/latest.txt
        python benchmarks/compare_frameworks.py > benchmark-results/comparison.txt
        python benchmarks/scaling_benchmark.py > benchmark-results/scaling.txt
    
    - name: Upload benchmark artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results/
        retention-days: 90
