name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]" pytest-timeout

      - name: Lint with ruff
        run: ruff check src/vedart tests

      - name: Format check with black
        run: black --check src/vedart tests

      - name: Type check with mypy
        run: mypy src/vedart --strict
        continue-on-error: true

      - name: Run tests
        run: |
          pytest tests/unit tests/integration -vv \
            --cov=src/vedart --cov-report=xml \
            --timeout=600 --maxfail=1

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
